GET https://localhost:7202

###
GET https://localhost:7202/hellous


###
# this should give "Hello Net24S"
GEt http://my-super-best-net24s-chapp.azurewebsites.net/

###
# this will fail (should say: dont maske me come up there...)

GEt http://my-super-best-net24s-chapp.azurewebsites.net/hellous